[buildPlans.spin-mono]
family = "Spin Mono"
spacing = "term"
serifs = "sans"
no-cv-ss = true
export-glyph-names = true

[buildPlans.spin-mono.variants]
inherits = "ss09"

[buildPlans.spin-mono.variants.design]
i = "zshaped"
q = "straight-serifless"
zero = "dotted"

[buildPlans.spin-mono.widths.condensed]
shape = 500
menu = 3
css = "condensed"

[buildPlans.spin-mono.widths.normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.spin-mono.widths.ultracondensed]
shape = 416
menu = 1
css = "ultra-condensed"

[buildPlans.spin-mono.widths.extracondensed]
shape = 456
menu = 2
css = "extra-condensed"

[buildPlans.spin-mono.widths.semicondensed]
shape = 548
menu = 4
css = "semi-condensed"

[buildPlans.spin-mono.widths.semiextended]
shape = 658
menu = 6
css = "semi-expanded"

[buildPlans.spin-mono.widths.extended]
shape = 720
menu = 7
css = "expanded"
